/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segurodevida;

import javax.swing.JOptionPane;

/**
 *
 * @author CBN
 */
public class SeguroVida extends javax.swing.JFrame {

    /**
     * Creates new form SeguroVida
     */
    SeguroDeVida seguroVida = new SeguroDeVida();
    boolean SiFumador = false, SiAlcoholico = false, SiDrogadicto = false ,SiCardiaco = false; 
    long ValorBase=0;
    public SeguroVida() {
        initComponents();
        txtValorBase.setText("");
        lbResultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgFumador = new javax.swing.ButtonGroup();
        rgAlcoholico = new javax.swing.ButtonGroup();
        rgDrogaticos = new javax.swing.ButtonGroup();
        rgCardiacos = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtValorBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbFumadorSi = new javax.swing.JRadioButton();
        rbFumadorNo = new javax.swing.JRadioButton();
        rbAlcoholicoSi = new javax.swing.JRadioButton();
        rbAlcoholicoNo = new javax.swing.JRadioButton();
        rbConsumidorSi = new javax.swing.JRadioButton();
        rbConsumidorNo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbCardiacoSi = new javax.swing.JRadioButton();
        rbCardiacoNo = new javax.swing.JRadioButton();
        chkAceptar = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Ingrese el valor base");

        txtValorBase.setText("jTextField1");

        jLabel3.setText("¿Es usted un fumador activo?");

        jLabel4.setText("¿Es usted alcoholico?");

        jLabel5.setText("¿Consume sustancias alucinògenas?");

        rgFumador.add(rbFumadorSi);
        rbFumadorSi.setText("Si");
        rbFumadorSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFumadorSiActionPerformed(evt);
            }
        });

        rgFumador.add(rbFumadorNo);
        rbFumadorNo.setText("No");

        rgAlcoholico.add(rbAlcoholicoSi);
        rbAlcoholicoSi.setText("Si");
        rbAlcoholicoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlcoholicoSiActionPerformed(evt);
            }
        });

        rgAlcoholico.add(rbAlcoholicoNo);
        rbAlcoholicoNo.setText("No");

        rgDrogaticos.add(rbConsumidorSi);
        rbConsumidorSi.setText("Si");

        rgDrogaticos.add(rbConsumidorNo);
        rbConsumidorNo.setText("No");

        jLabel6.setText("¿Tiene antecedentes cardiacos?");

        rgCardiacos.add(rbCardiacoSi);
        rbCardiacoSi.setText("Si");
        rbCardiacoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCardiacoSiActionPerformed(evt);
            }
        });

        rgCardiacos.add(rbCardiacoNo);
        rbCardiacoNo.setText("No");
        rbCardiacoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCardiacoNoActionPerformed(evt);
            }
        });

        chkAceptar.setText("Acepta los terminos y condiciones");
        chkAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAceptarActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular Seguro de vida");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbResultado.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultado)
                    .addComponent(rbCardiacoNo)
                    .addComponent(rbCardiacoSi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(rbFumadorSi)
                                    .addComponent(rbFumadorNo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbAlcoholicoNo)
                                            .addComponent(rbAlcoholicoSi)))))
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbConsumidorSi)
                            .addComponent(jLabel5)
                            .addComponent(rbConsumidorNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAceptar)
                        .addGap(55, 55, 55)
                        .addComponent(btnCalcular)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbAlcoholicoSi, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbConsumidorSi))
                    .addComponent(rbFumadorSi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAlcoholicoNo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFumadorNo))
                            .addComponent(rbConsumidorNo))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCardiacoSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCardiacoNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAceptar)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lbResultado)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAlcoholicoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlcoholicoSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAlcoholicoSiActionPerformed

    private void rbFumadorSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFumadorSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFumadorSiActionPerformed

    private void chkAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAceptarActionPerformed
        // TODO add your handling code here:
        if(chkAceptar.isSelected()){
            btnCalcular.setEnabled(true);
        }else{
            btnCalcular.setEnabled(false);
        }
    }//GEN-LAST:event_chkAceptarActionPerformed

    private void rbCardiacoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCardiacoSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCardiacoSiActionPerformed

    private void rbCardiacoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCardiacoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCardiacoNoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            CalcularSeguro();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Faltan campos por digitar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void CalcularSeguro(){
        ValorBase = Long.parseLong(txtValorBase.getText());
        if(rbFumadorSi.isSelected()){
            SiFumador=true;
        }else{
            SiFumador=false;
        }
        if(rbAlcoholicoSi.isSelected()){
            SiAlcoholico=true;
        }else{
            SiAlcoholico=false;
        }
        if(rbConsumidorSi.isSelected()){
            SiDrogadicto=true;
        }else{
            SiDrogadicto=false;
        }
        if(rbCardiacoSi.isSelected()){
            SiCardiaco=true;
        }else{
            SiCardiaco=false;
        }
        FrameOut FO = new FrameOut(Long.toString(seguroVida.Calcular(ValorBase,SiFumador,SiAlcoholico,SiDrogadicto,SiCardiaco)));
        FO.setVisible(true);
    }
    
    /**
     * ç
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeguroVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeguroVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeguroVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeguroVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeguroVida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBox chkAceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JRadioButton rbAlcoholicoNo;
    private javax.swing.JRadioButton rbAlcoholicoSi;
    private javax.swing.JRadioButton rbCardiacoNo;
    private javax.swing.JRadioButton rbCardiacoSi;
    private javax.swing.JRadioButton rbConsumidorNo;
    private javax.swing.JRadioButton rbConsumidorSi;
    private javax.swing.JRadioButton rbFumadorNo;
    private javax.swing.JRadioButton rbFumadorSi;
    private javax.swing.ButtonGroup rgAlcoholico;
    private javax.swing.ButtonGroup rgCardiacos;
    private javax.swing.ButtonGroup rgDrogaticos;
    private javax.swing.ButtonGroup rgFumador;
    private javax.swing.JTextField txtValorBase;
    // End of variables declaration//GEN-END:variables
}
